name: Windows RDP

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Enable RDP
        run: |
          Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server' -Name "fDenyTSConnections" -Value 0
          Enable-NetFirewallRule -DisplayGroup "Remote Desktop"

      - name: Set Password
        run: |
          net user runneradmin P@ssw0rd!

      - name: Install Tailscale
        run: |
          Invoke-WebRequest -Uri "https://pkgs.tailscale.com/stable/tailscale-setup-latest.exe" -OutFile "tailscale.exe"
          Start-Process -FilePath ".\tailscale.exe" -ArgumentList "/quiet" -Wait
          Start-Sleep -Seconds 20
          & "C:\Program Files\Tailscale\tailscale.exe" up --authkey ${{ secrets.TAILSCALE_AUTH_KEY }} --unattended

      - name: Get Tailscale IP
        run: |
          Start-Sleep -Seconds 10
          & "C:\Program Files\Tailscale\tailscale.exe" ip -4

      - name: Keep Alive
        run: |
          Start-Sleep -Seconds 21600
