name: Windows RDP

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Enable RDP
        run: |
          Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server' -Name "fDenyTSConnections" -Value 0
          Enable-NetFirewallRule -DisplayGroup "Remote Desktop"

      - name: Set Password
        run: |
          net user runneradmin P@ssw0rd!

      - name: Install SSH
        run: |
          Add-WindowsCapability -Online -Name OpenSSH.Client~~~~0.0.1.0
          Add-WindowsCapability -Online -Name OpenSSH.Server~~~~0.0.1.0

      - name: Start Tunnel
        run: |
          ssh -o StrictHostKeyChecking=no -R 0:localhost:3389 nokey@localhost.run
        timeout-minutes: 360
